
set(SDL2_LIBRARY "sdl2")
set(SDL2_INCLUDE_DIR " ")
set(SDL2_FOUND TRUE)

set(FREETYPE_LIBRARY "freetype")
set(FREETYPE_INCLUDE_DIRS " ")
set(FREETYPE_FOUND TRUE)

set(ZLIB_LIBRARY "zlib")
set(ZLIB_INCLUDE_DIR " ")
set(ZLIB_FOUND TRUE)

set(M_LIBRARY "m")
set(M_INCLUDE_DIR " ")
set(M_FOUND TRUE)

set(WASM 1)
set(WEBGL2 0)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_ZLIB=1 -std=c++17 -s USE_WEBGL2=${WEBGL2} -s WASM=${WASM} -s ALLOW_MEMORY_GROWTH=${WASM} -s TOTAL_MEMORY=1GB -s FULL_ES3=0")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_ZLIB=1 -s USE_WEBGL2=${WEBGL2} -s WASM=${WASM} -s ALLOW_MEMORY_GROWTH=${WASM} -s TOTAL_MEMORY=1GB -s FULL_ES3=0")
set(CMAKE_EXE_LINK_FLAGS "${CMAKE_EXE_LINK_FLAGS} -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_ZLIB=1 -lopenal -s USE_WEBGL2=${WEBGL2} -s WASM=${WASM} -s ALLOW_MEMORY_GROWTH=${WASM} -s TOTAL_MEMORY=1GB -s FULL_ES3=0")

if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g4 -s DEMANGLE_SUPPORT=1 -s ASSERTIONS=2 -s NO_EXIT_RUNTIME=0")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g4 -s DEMANGLE_SUPPORT=1 -s ASSERTIONS=2 -s NO_EXIT_RUNTIME=0")
	set(CMAKE_EXE_LINK_FLAGS "${CMAKE_EXE_LINK_FLAGS} -g4 -s DEMANGLE_SUPPORT=1 -s ASSERTIONS=2 -s NO_EXIT_RUNTIME=0")
elseif("${CMAKE_BUILD_TYPE}" MATCHES "Release")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 --llvm-lto 1")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 --llvm-lto 1")
	set(CMAKE_EXE_LINK_FLAGS "${CMAKE_EXE_LINK_FLAGS} --llvm-lto 1")
endif()

SET(CMAKE_EXECUTABLE_SUFFIX ".html")
